package com.arjun.signagekioskautousb;
import android.annotation.SuppressLint;import android.app.Activity;import android.content.Intent;import android.graphics.Color;import android.os.*;import android.os.Environment;import android.view.*;import android.webkit.*;import android.widget.TextView;import java.io.File;
public class MainActivity extends Activity {
 public static final String PLAYER_URL="http://ads.asianpaints.com.np/player.html"; private WebView webView;private TextView statusText;private File storageRoot;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_FULLSCREEN|WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON|WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD);setContentView(R.layout.activity_main_auto);webView=findViewById(R.id.webView);statusText=findViewById(R.id.statusText);hide();storageRoot=detect();setup();statusText.setText(storageRoot==null?"USB not detected":"USB: "+storageRoot.getAbsolutePath());webView.loadUrl(PLAYER_URL);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(new Intent(this,StartupService.class));else startService(new Intent(this,StartupService.class));}catch(Exception ignored){}}
 private File detect(){File[]ds=getExternalFilesDirs(null);if(ds!=null)for(File d:ds)if(d!=null&&Environment.isExternalStorageRemovable(d)){File x=new File(d,"SignageKiosk");if(x.mkdirs()||x.isDirectory()){new File(x,"media").mkdirs();new File(x,"data").mkdirs();new File(x,"temp").mkdirs();return x;}}return null;}
 @SuppressLint({"SetJavaScriptEnabled","JavascriptInterface"})private void setup(){WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);webView.setBackgroundColor(Color.BLACK);webView.setWebChromeClient(new WebChromeClient());webView.setWebViewClient(new WebViewClient());webView.addJavascriptInterface(new Bridge(),"AndroidStorage");}
 public class Bridge{@JavascriptInterface public String getStoragePath(){return storageRoot==null?"":storageRoot.getAbsolutePath();}@JavascriptInterface public boolean isUsbAvailable(){return storageRoot!=null&&storageRoot.exists();}@JavascriptInterface public String getPlayerUrl(){return PLAYER_URL;}}
 private void hide(){getWindow().getDecorView().setSystemUiVisibility(5894|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}@Override public void onWindowFocusChanged(boolean h){super.onWindowFocusChanged(h);if(h)hide();}@Override public boolean onKeyDown(int k,KeyEvent e){if(k==KeyEvent.KEYCODE_BACK)return true;return super.onKeyDown(k,e);}
}
