plugins {
    id 'com.android.application'
}

android {
    namespace 'com.arjun.signagekioskoffline'
    compileSdk 34

    defaultConfig {
        applicationId 'com.arjun.signagekioskoffline'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '1.0-offline-usb'
    }
}
